# .github/workflows/coverage-report-deploy.yml
name: 🧪 Deploy Coverage Report to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          go mod download
          go mod tidy

      - name: Run tests and generate coverage report
        run: |
          mkdir -p test-reports
          # テスト実行 & カバレッジ生成🔥
          go test -v -coverprofile=test-reports/coverage.out ./... 2>&1 | tee test-reports/test-output.txt

          # カバレッジレポート(HTML)生成✨
          go tool cover -html=test-reports/coverage.out -o test-reports/coverage.html

          # カバレッジパーセンテージ計算📊
          COVERAGE=$(go tool cover -func=test-reports/coverage.out | grep total | awk '{print $3}')
          echo "Total Coverage: $COVERAGE"
          echo "$COVERAGE" > test-reports/coverage-percent.txt

          # テスト結果のサマリー生成💕
          if grep -q "FAIL" test-reports/test-output.txt; then
            echo "FAILED" > test-reports/test-status.txt
          else
            echo "PASSED" > test-reports/test-status.txt
          fi

      - name: Create index page
        run: |
          # カバレッジとステータスを取得✨
          COVERAGE=$(cat test-reports/coverage-percent.txt)
          TEST_STATUS=$(cat test-reports/test-status.txt)

          # ステータスに応じた絵文字とカラー設定🎀
          if [ "$TEST_STATUS" = "PASSED" ]; then
            STATUS_EMOJI="✅"
            STATUS_COLOR="#48bb78"
            STATUS_TEXT="All Tests Passed"
          else
            STATUS_EMOJI="❌"
            STATUS_COLOR="#f56565"
            STATUS_TEXT="Tests Failed"
          fi

          cat > test-reports/index.html << EOF
          <!DOCTYPE html>
          <html lang="ja">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Go CLI Sample - Test Reports</title>
              <style>
                  /* グラスモーフィズム最高〜！✨💎 */
                  @keyframes gradientMove {
                      0% { background-position: 0% 50%; }
                      50% { background-position: 100% 50%; }
                      100% { background-position: 0% 50%; }
                  }

                  * {
                      margin: 0;
                      padding: 0;
                      box-sizing: border-box;
                  }

                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
                      max-width: 900px;
                      margin: 0 auto;
                      padding: 40px 20px;
                      /* めっちゃエモいアニメーショングラデーション🌈✨ */
                      background: linear-gradient(-45deg, #667eea, #764ba2, #f093fb, #4facfe);
                      background-size: 400% 400%;
                      animation: gradientMove 15s ease infinite;
                      min-height: 100vh;
                  }

                  .container {
                      /* グラスモーフィズムでキラキラに〜💎 */
                      background: rgba(255, 255, 255, 0.25);
                      backdrop-filter: blur(10px) saturate(180%);
                      -webkit-backdrop-filter: blur(10px) saturate(180%);
                      border-radius: 20px;
                      padding: 50px;
                      box-shadow:
                          0 8px 32px 0 rgba(31, 38, 135, 0.37),
                          inset 0 0 0 1px rgba(255, 255, 255, 0.18);
                      border: 1px solid rgba(255, 255, 255, 0.3);
                  }

                  h1 {
                      color: #ffffff;
                      margin-bottom: 10px;
                      font-size: 2.8em;
                      font-weight: 800;
                      text-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
                  }

                  .subtitle {
                      color: rgba(255, 255, 255, 0.95);
                      margin-bottom: 40px;
                      font-size: 1.3em;
                      font-weight: 500;
                      text-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
                  }

                  .stats {
                      display: flex;
                      gap: 20px;
                      margin: 40px 0;
                  }

                  .stat-box {
                      flex: 1;
                      /* グラスモーフィズムのstat-box💕 */
                      background: rgba(255, 255, 255, 0.2);
                      backdrop-filter: blur(10px);
                      -webkit-backdrop-filter: blur(10px);
                      color: white;
                      padding: 30px 20px;
                      border-radius: 16px;
                      text-align: center;
                      border: 1px solid rgba(255, 255, 255, 0.3);
                      box-shadow:
                          0 8px 32px 0 rgba(31, 38, 135, 0.2),
                          inset 0 0 0 1px rgba(255, 255, 255, 0.1);
                      transition: all 0.3s ease;
                  }

                  .stat-box:hover {
                      transform: translateY(-5px);
                      box-shadow:
                          0 12px 40px 0 rgba(31, 38, 135, 0.3),
                          inset 0 0 0 1px rgba(255, 255, 255, 0.2);
                  }

                  .stat-value {
                      font-size: 3em;
                      font-weight: 900;
                      margin: 15px 0;
                      text-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
                  }

                  .stat-label {
                      font-size: 0.95em;
                      opacity: 0.95;
                      font-weight: 500;
                      text-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
                  }

                  .card {
                      /* カードもグラスモーフィズムで統一〜🎀 */
                      background: rgba(255, 255, 255, 0.3);
                      backdrop-filter: blur(10px);
                      -webkit-backdrop-filter: blur(10px);
                      border-left: 4px solid rgba(255, 255, 255, 0.5);
                      padding: 25px;
                      margin: 20px 0;
                      border-radius: 16px;
                      border: 1px solid rgba(255, 255, 255, 0.25);
                      box-shadow:
                          0 8px 32px 0 rgba(31, 38, 135, 0.15),
                          inset 0 0 0 1px rgba(255, 255, 255, 0.1);
                      transition: all 0.3s ease;
                  }

                  .card:hover {
                      transform: translateY(-3px) translateX(5px);
                      box-shadow:
                          0 12px 40px 0 rgba(31, 38, 135, 0.25),
                          inset 0 0 0 1px rgba(255, 255, 255, 0.2);
                      background: rgba(255, 255, 255, 0.35);
                  }

                  .status-badge {
                      display: inline-block;
                      padding: 10px 20px;
                      border-radius: 25px;
                      background: ${STATUS_COLOR};
                      color: white;
                      font-weight: bold;
                      margin: 10px 0;
                      box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
                  }

                  a {
                      color: #ffffff;
                      text-decoration: none;
                      font-weight: 700;
                      font-size: 1.2em;
                      text-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
                      transition: all 0.3s ease;
                  }

                  a:hover {
                      color: #f0f0f0;
                      text-shadow: 0 2px 12px rgba(0, 0, 0, 0.3);
                  }

                  .description {
                      color: rgba(255, 255, 255, 0.9);
                      margin-top: 15px;
                      line-height: 1.7;
                      font-size: 0.95em;
                      text-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
                  }

                  .emoji {
                      font-size: 1.6em;
                      margin-right: 12px;
                      filter: drop-shadow(0 2px 4px rgba(0, 0, 0, 0.1));
                  }

                  /* レスポンシブ対応もバッチリ📱✨ */
                  @media (max-width: 768px) {
                      .stats {
                          flex-direction: column;
                      }

                      .container {
                          padding: 30px 25px;
                      }

                      h1 {
                          font-size: 2em;
                      }
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🧪 Go CLI Sample Test Reports</h1>
                  <p class="subtitle">テストカバレッジレポート 📊✨</p>

                  <div class="stats">
                      <div class="stat-box">
                          <div class="stat-label">Test Coverage</div>
                          <div class="stat-value">${COVERAGE}</div>
                          <div class="stat-label">コードカバレッジ率 🎯</div>
                      </div>
                      <div class="stat-box">
                          <div class="stat-label">Test Status</div>
                          <div class="stat-value">${STATUS_EMOJI}</div>
                          <div class="stat-label">${STATUS_TEXT}</div>
                      </div>
                  </div>

                  <div class="card">
                      <a href="coverage.html">
                          <span class="emoji">📈</span>
                          カバレッジレポートを見る
                      </a>
                      <p class="description">
                          コードのテストカバレッジを視覚的に確認できます。<br>
                          どの部分がテストされているか、一目でわかるよ〜！🎀
                      </p>
                  </div>

                  <div class="card">
                      <a href="test-output.txt">
                          <span class="emoji">📝</span>
                          テスト出力ログを見る
                      </a>
                      <p class="description">
                          テストの詳細な出力結果をチェックできます。<br>
                          エラーが出てたらここで確認してね！💪✨
                      </p>
                  </div>

                  <div class="card">
                      <p style="color: #4a5568; margin: 0;">
                          <span class="emoji">🔗</span>
                          <strong>GitHub Repository:</strong><br>
                          <a href="https://github.com/Sunwood-ai-labs/go-cli-sample" target="_blank">
                              Sunwood-ai-labs/go-cli-sample
                          </a>
                      </p>
                  </div>
              </div>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'test-reports'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
